#!/usr/bin/env python3
"""Build an Apple Live Photo resource pair from a still image and a motion clip.

The output directory contains a JPEG and MOV that share an Apple asset identifier.
Import both files together into Apple Photos to preserve the Live Photo pairing.

Example:
  python3 make_live_photo.py --photo scene.jpg --video scene.mp4 \
      --output-dir scene-LivePhoto

This runs only on macOS. It uses ffmpeg for the MOV container and makelive,
which uses Apple's native frameworks to write the required Live Photo metadata.
"""
import argparse
import platform
import shutil
import subprocess
from pathlib import Path


def run(command: list[str]) -> None:
    result = subprocess.run(command)
    if result.returncode:
        raise SystemExit(f"Command failed ({result.returncode}): {' '.join(command)}")


def require_program(name: str) -> str:
    path = shutil.which(name)
    if not path:
        raise SystemExit(f"Missing {name}. Install it and make sure it is on PATH.")
    return path


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Create a verified Apple Live Photo JPEG/MOV pair from a still and MP4 clip."
    )
    parser.add_argument("--photo", required=True, help="Still image for the Live Photo (JPEG or PNG)")
    parser.add_argument("--video", required=True, help="Animated clip (MP4 or MOV)")
    parser.add_argument("--output-dir", required=True, help="New directory for the paired JPEG and MOV")
    parser.add_argument("--name", default="IMG", help="Output filename prefix, default IMG")
    args = parser.parse_args()

    if platform.system() != "Darwin":
        raise SystemExit(
            "A true Apple Live Photo can only be packaged on macOS. "
            "Use the accompanying MP4 for social uploads on this system."
        )

    photo = Path(args.photo).resolve()
    video = Path(args.video).resolve()
    output_dir = Path(args.output_dir).resolve()
    if not photo.is_file() or not video.is_file():
        parser.error("--photo and --video must both point to existing files")
    if output_dir.exists() and any(output_dir.iterdir()):
        parser.error("--output-dir must be empty or not exist, so an existing Live Photo is not overwritten")

    ffmpeg = require_program("ffmpeg")
    makelive = require_program("makelive")
    output_dir.mkdir(parents=True, exist_ok=True)
    still = output_dir / f"{args.name}.JPG"
    motion = output_dir / f"{args.name}.MOV"

    # Create fresh resources. makelive modifies copies in place, never the source files.
    run([ffmpeg, "-y", "-i", str(photo), "-frames:v", "1", "-q:v", "2", str(still)])
    run([
        ffmpeg, "-y", "-i", str(video), "-map", "0:v:0", "-an",
        "-c:v", "libx264", "-pix_fmt", "yuv420p", "-movflags", "+faststart",
        str(motion),
    ])
    run([makelive, str(still), str(motion)])

    manifest = output_dir / "README.txt"
    manifest.write_text(
        "Apple Live Photo resource pair\n"
        "Import the JPG and MOV together into Apple Photos. Keep both files in the "
        "same folder until import; they form one Live Photo there.\n"
        "For Xiaohongshu, Instagram, TikTok, and other social platforms, upload the "
        "separate MP4 generated by make_gif.py for the most reliable moving post.\n",
        encoding="ascii",
    )
    print(f"OK Apple Live Photo pair: {still} + {motion}")


if __name__ == "__main__":
    main()
